name: Build Windows Executables with Nuitka
permissions: write-all
on:
  push:
    branches:
      - master
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install imageio
      - name: Run Nuitka for Deserializer
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: flatc_deserializer.py
          onefile: true
          enable-plugins: tk-inter
          include-data-dir: |
            .\localization=localization
            .\images=images
          product-name: Flatbuffers Deserializer
          product-version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
          file-description: Program for deserialization of Flatbuffers binary files based on single schema.
          windows-icon-from-ico: "images/flatbuffers-logo-clean.png"
      - name: Run Nuitka for Downloader
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: flatc_downloader.py
          onefile: true
          enable-plugins: tk-inter
          include-data-dir: |
            .\localization=localization
            .\images=images
          product-name: Flatbuffers Schema Compiler Downloader
          product-version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
          file-description: Program for downloading latest version of Flatbuffers schema compiler for Windows.
          windows-icon-from-ico: "images/flatbuffers-downloader-logo-clean.png"
      - name: Run Nuitka for Batch Deserializer
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: flatc_deserializer_batch.py
          onefile: true
          enable-plugins: tk-inter
          include-data-dir: |
            .\localization=localization
            .\images=images
          product-name: Flatbuffers Batch Deserializer
          product-version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
          file-description: Program for deserialization of Flatbuffers binary files based on multiple schemas.
          windows-icon-from-ico: "images/flatbuffers-batch-logo-clean.png"
      - name: Move Executables from build to root directory
        run: |
          move build\flatc_deserializer.exe .
          move build\flatc_deserializer_batch.exe .
          move build\flatc_downloader.exe .
          rd /s /q build
        shell: cmd
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-nuitka
          prerelease: false
          title: Latest Nuitka Build
          files: |
            flatc_deserializer.exe
            flatc_deserializer_batch.exe
            flatc_downloader.exe