name: Build Windows Executables
permissions: write-all
on:
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install pillow tqdm i18nice[YAML] pyinstaller
      - name: Run PyInstaller for Deserializer and Downloader
        run: |
          pyinstaller --onefile --name="flatc_deserializer" --console --icon=images\flatbuffers-logo-clean.png --add-data="images:images" --add-data="localization:localization" flatc_deserializer.py
          pyinstaller --onefile --name="flatc_downloader" --console --icon=images\flatbuffers-downloader-logo-clean.png --add-data="images:images" --add-data="localization:localization" flatc_downloader.py
          pyinstaller --onefile --name="flatc_deserializer_batch" --console --icon=images\flatbuffers-batch-logo-clean.png --add-data="images:images" --add-data="localization:localization" flatc_deserializer_batch.py
      - name: Move Deserializer and Downloader Executables from dist to root directory and delete dist directory
        run: |
          move dist\flatc_deserializer.exe .
          move dist\flatc_downloader.exe .
          move dist\flatc_deserializer_batch.exe .
          rd /s /q dist
        shell: cmd
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Build
          files: |
            flatc_deserializer.exe
            flatc_downloader.exe
            flatc_deserializer_batch.exe