name: Build Windows Executables with PyInstaller
permissions: write-all
on:
  push:
    branches:
      - master
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Run PyInstaller for Deserializer, Downloader and Batch Deserializer
        run: |
          set PYTHONOPTIMIZE=2
          pyinstaller --onefile --name="flatc_deserializer" --console --icon=src\flatc_deserializer\images\flatbuffers-logo-clean.png --add-data="src\flatc_deserializer\images:images" --add-data="src\flatc_deserializer\localization:localization" deserializer.py
          pyinstaller --onefile --name="flatc_downloader" --console --icon=src\flatc_deserializer\images\flatbuffers-downloader-logo-clean.png --add-data="src\flatc_deserializer\images:images" --add-data="src\flatc_deserializer\localization:localization" downloader.py
          pyinstaller --onefile --name="flatc_deserializer_batch" --console --icon=src\flatc_deserializer\images\flatbuffers-batch-logo-clean.png --add-data="src\flatc_deserializer\images:images" --add-data="src\flatc_deserializer\localization:localization" deserializer_batch.py
      - name: Install additional GUI requirements
        run: |
          pip install pywinstyles
      - name: Run PyInstaller for GUI
        run: |
          set PYTHONOPTIMIZE=2
          pyinstaller --onefile --noconsole --name="flatc_deserializer_frontend" --hiddenimport pywinstyles --icon=src\flatc_deserializer\images\flatbuffers-logo-clean.png --add-data="src\flatc_deserializer\images:images" --add-data="src\flatc_deserializer\localization:localization" deserializer_frontend.py
      - name: Move Executables from dist to root directory and delete dist directory
        run: |
          move dist\flatc_deserializer.exe .
          move dist\flatc_downloader.exe .
          move dist\flatc_deserializer_batch.exe .
          move dist\flatc_deserializer_frontend.exe .
          rd /s /q dist
        shell: cmd
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Build
          files: |
            flatc_deserializer.exe
            flatc_downloader.exe
            flatc_deserializer_batch.exe
            flatc_deserializer_frontend.exe